- repo: https://github.com/prettier/maven-plugin
  rev: v2.0.0  # Reemplaza por la versión más reciente de Prettier
  hooks:
    - id: checkstyle
      name: Java Checkstyle
      files: \.(java)$
      args: ['--config', '.checkstyle.xml']

- repo: https://github.com/prettier/prettier
  rev: v2.0.0
  hooks:
    - id: prettier
      name: Prettier Formatting
      files: \.(java|xml|md|js)$
